import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.scss";
import Link from "next/link";
import Image from "next/image";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          <title>Online Shop</title>
          <Script src="/api_faker.js"></Script>
      </head>
      <body>
        <header>
            <div className={"header-container"}>
                <Link href="/catalog">
                    <button className={"header-button"}>
                        <Image className={"header-button-image"} src={"/header-button.svg"} alt={"Button"} width={28} height={32} />
                    </button>
                </Link>
                <Link href="/">
                    <Image className={"header-image"} src={"/images/Logo.svg"} alt="Logo" width={145} height={32}/>
                </Link>
            </div>
        </header>
        {children}
        <footer>
            <div className={"footer-container"}>
                <nav className={"footer-container-nav"}>
                    <Link href="/about">About Us</Link>
                    <Link href="/contacts">Contacts</Link>
                    <Link href="/terms">Terms & Conditions</Link>
                    <Link href="/privacy">Privacy Policy</Link>
                </nav>
                <p className={"footer-text"}>© Copyright 2023 Lorem Ipsum inc.</p>
            </div>
        </footer>
      </body>
    </html>
  );
}
